# Generated by Django 6.0.3 on 2026-03-12 15:51

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitabilityscores',
            name='economy_score',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('employment_rate'), '*', models.Value(0.25)), '+', django.db.models.expressions.CombinedExpression(models.F('income'), '*', models.Value(0.35))), '+', django.db.models.expressions.CombinedExpression(models.F('inflation'), '*', models.Value(0.4))), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='habitabilityscores',
            name='environment_score',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('air_quality'), '*', models.Value(0.2)), '+', django.db.models.expressions.CombinedExpression(models.F('water_quality'), '*', models.Value(0.15))), '+', django.db.models.expressions.CombinedExpression(models.F('land_fertility'), '*', models.Value(0.25))), '+', django.db.models.expressions.CombinedExpression(models.F('waste_management'), '*', models.Value(0.4))), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='habitabilityscores',
            name='infrastructure_score',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('education'), '*', models.Value(0.3)), '+', django.db.models.expressions.CombinedExpression(models.F('healthcare'), '*', models.Value(0.3))), '+', django.db.models.expressions.CombinedExpression(models.F('transportation'), '*', models.Value(0.4))), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='habitabilityscores',
            name='security_score',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('crime'), '*', models.Value(0.3)), '+', django.db.models.expressions.CombinedExpression(models.F('politics'), '*', models.Value(0.25))), '+', django.db.models.expressions.CombinedExpression(models.F('disaster_risks'), '*', models.Value(0.3))), '+', django.db.models.expressions.CombinedExpression(models.F('civic_engagement'), '*', models.Value(0.15))), output_field=models.FloatField()),
        ),
    ]
