# Generated by Django 6.0.3 on 2026-03-12 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitability', '0002_habitabilityscores_economy_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitabilityscores',
            name='county',
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('neighborhood_id', models.AutoField(primary_key=True, serialize=False)),
                ('neighborhood_name', models.CharField(max_length=100, unique=True)),
                ('postcode', models.CharField(blank=True, max_length=7, null=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='habitability.region')),
            ],
        ),
        migrations.AddField(
            model_name='habitabilityscores',
            name='neighborhood',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habitability_score', to='habitability.neighborhood'),
        ),
        migrations.DeleteModel(
            name='Neighbourhood',
        ),
    ]
