# Generated by Django 6.0.3 on 2026-03-12 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitability', '0003_remove_habitabilityscores_county_neighborhood_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighborhood',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neighborhoods', to='habitability.region'),
        ),
    ]
