# Generated by Django 6.0.3 on 2026-03-12 18:40

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitability', '0004_alter_neighborhood_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitabilityscores',
            name='overall_score',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('economy_score'), '*', models.Value(0.3)), '+', django.db.models.expressions.CombinedExpression(models.F('environment_score'), '*', models.Value(0.2))), '+', django.db.models.expressions.CombinedExpression(models.F('infrastructure_score'), '*', models.Value(0.3))), '+', django.db.models.expressions.CombinedExpression(models.F('security_score'), '*', models.Value(0.2))), output_field=models.FloatField()),
        ),
    ]
