# Generated by Django 6.0.3 on 2026-03-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitability', '0005_habitabilityscores_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighborhood',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
