# Generated by Django 6.0.3 on 2026-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitability', '0006_neighborhood_lat_neighborhood_lon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcodeCountyMapping',
            fields=[
                ('outcode', models.CharField(max_length=4, primary_key=True, serialize=False, unique=True)),
                ('county', models.CharField(max_length=50)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Outcode County Mappings',
            },
        ),
    ]
