# Generated by Django 6.0.3 on 2026-03-11 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitabilityScores',
            fields=[
                ('score_id', models.AutoField(primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=100, unique=True)),
                ('employment_rate', models.FloatField()),
                ('income', models.FloatField()),
                ('inflation', models.FloatField()),
                ('air_quality', models.FloatField()),
                ('water_quality', models.FloatField()),
                ('land_fertility', models.FloatField()),
                ('waste_management', models.FloatField()),
                ('education', models.FloatField()),
                ('healthcare', models.FloatField()),
                ('transportation', models.FloatField()),
                ('crime', models.FloatField()),
                ('politics', models.FloatField()),
                ('disaster_risks', models.FloatField()),
                ('civic_engagement', models.FloatField()),
                ('date_scored', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Neighbourhood',
            fields=[
                ('neighbourhood_id', models.AutoField(primary_key=True, serialize=False)),
                ('county', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=7)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Neighbourhoods', to='accounts.region')),
            ],
        ),
    ]
