# Generated by Django 6.0.3 on 2026-03-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HabitabilityScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(unique=True)),
                ('employment_rate', models.FloatField()),
                ('income', models.FloatField()),
                ('inflation', models.FloatField()),
                ('air_quality', models.FloatField()),
                ('water_quality', models.FloatField()),
                ('land_fertility', models.FloatField()),
                ('waste_management', models.FloatField()),
                ('education', models.FloatField()),
                ('healthcare', models.FloatField()),
                ('transportation', models.FloatField()),
                ('crime', models.FloatField()),
                ('politics', models.FloatField()),
                ('disaster_risks', models.FloatField()),
                ('civic_engagement', models.FloatField()),
            ],
        ),
    ]
