# Generated by Django 6.0.3 on 2026-03-19 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailotp'),
        ('habitability', '0005_habitabilityscores_overall_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='habitability.neighborhood'),
        ),
    ]
