import csv
from datetime import date
from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from habitability.models import Region, Neighborhood, HabitabilityScores

# Generated by Charlie, using GPT-5.4
# Prompt: "Write a command that I can use with manage.py, to import HabitabilityData.csv into the database. The county column corresponds with the 'Region' model."

class Command(BaseCommand):
    help = 'Import habitability data from HabitabilityData.csv'

    def add_arguments(self, parser):
        parser.add_argument(
            'csv_file',
            type=str,
            help='Path to the HabitabilityData.csv file to import'
        )
        parser.add_argument(
            '--date',
            type=str,
            default=str(date.today()),
            help='Date for the habitability scores (YYYY-MM-DD format, default: today)'
        )
        parser.add_argument(
            '--update',
            action='store_true',
            help='Update existing HabitabilityScores if they already exist'
        )

    @transaction.atomic
    def handle(self, *args, **options):
        csv_file = options['csv_file']
        score_date = options['date']
        update_existing = options['update']

        try:
            with open(csv_file, 'r', encoding='utf-8') as file:
                reader = csv.DictReader(file)
                if not reader.fieldnames:
                    raise CommandError('CSV file appears to be empty')

                created_count = 0
                updated_count = 0
                skipped_count = 0

                for row_num, row in enumerate(reader, start=2):  # start=2 to account for header
                    try:
                        county = row.get('County', '').strip()
                        if not county:
                            self.stdout.write(
                                self.style.WARNING(f'Row {row_num}: Skipped - empty County field')
                            )
                            skipped_count += 1
                            continue

                        # Get or create Region using County name
                        region, _ = Region.objects.get_or_create(
                            region_name=county,
                            defaults={'region_name': county}
                        )

                        # Get or create Neighborhood using County name
                        neighborhood, _ = Neighborhood.objects.get_or_create(
                            neighborhood_name=county,
                            defaults={'region': region}
                        )

                        # Prepare habitability scores data
                        scores_data = {
                            'neighborhood': neighborhood,
                            'employment_rate': float(row.get('Employment_Rate', 0)),
                            'income': float(row.get('Income', 0)),
                            'inflation': float(row.get('Inflation', 0)),
                            'air_quality': float(row.get('Air_Quality', 0)),
                            'water_quality': float(row.get('Water_Quality', 0)),
                            'land_fertility': float(row.get('Land_Fertility', 0)),
                            'waste_management': float(row.get('Waste_Management', 0)),
                            'education': float(row.get('Education', 0)),
                            'healthcare': float(row.get('Healthcare', 0)),
                            'transportation': float(row.get('Transportation', 0)),
                            'crime': float(row.get('Crime', 0)),
                            'politics': float(row.get('Politics', 0)),
                            'disaster_risks': float(row.get('Disaster_Risks', 0)),
                            'civic_engagement': float(row.get('Civic_Engagement', 0)),
                            'date_scored': score_date,
                        }

                        # Get or create HabitabilityScores
                        score_obj, created = HabitabilityScores.objects.get_or_create(
                            neighborhood=neighborhood,
                            defaults=scores_data
                        )

                        if created:
                            created_count += 1
                            self.stdout.write(
                                self.style.SUCCESS(f'Row {row_num}: Created HabitabilityScores for {county}')
                            )
                        else:
                            if update_existing:
                                # Update existing record
                                for key, value in scores_data.items():
                                    setattr(score_obj, key, value)
                                score_obj.save()
                                updated_count += 1
                                self.stdout.write(
                                    self.style.SUCCESS(f'Row {row_num}: Updated HabitabilityScores for {county}')
                                )
                            else:
                                skipped_count += 1
                                self.stdout.write(
                                    self.style.WARNING(f'Row {row_num}: Skipped {county} (already exists, use --update to override)')
                                )

                    except ValueError as e:
                        self.stdout.write(
                            self.style.ERROR(f'Row {row_num}: Error parsing numeric values - {str(e)}')
                        )
                        skipped_count += 1
                    except Exception as e:
                        self.stdout.write(
                            self.style.ERROR(f'Row {row_num}: Unexpected error - {str(e)}')
                        )
                        skipped_count += 1

                # Print summary
                self.stdout.write(self.style.SUCCESS('\n=== Import Summary ==='))
                self.stdout.write(self.style.SUCCESS(f'Created: {created_count}'))
                self.stdout.write(self.style.SUCCESS(f'Updated: {updated_count}'))
                self.stdout.write(self.style.WARNING(f'Skipped: {skipped_count}'))

        except FileNotFoundError:
            raise CommandError(f'CSV file not found: {csv_file}')
        except Exception as e:
            raise CommandError(f'Error importing CSV: {str(e)}')
