# Generated by Django 6.0.3 on 2026-03-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_severity_report_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='neighbourhood',
        ),
        migrations.AddField(
            model_name='report',
            name='lat',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='lon',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='postcode',
            field=models.CharField(default='B29', max_length=7),
            preserve_default=False,
        ),
    ]
